package contract

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// TypeScriptDeclaration is generated from the public Go contract, never from
// provider configuration or an OpenAPI client schema.
func TypeScriptDeclaration() string {
	var out strings.Builder
	out.WriteString("// Generated by go generate ./internal/canvas/contract. Do not edit.\n")
	fmt.Fprintf(&out, "export const GENERATION_CONTRACT_VERSION = %d;\nexport const GENERATION_LIMITS = { nodeTitle: %d, prompt: %d, canvasOperations: %d } as const;\n\n", GenerationVersion, MaxNodeTitleRunes, MaxPromptRunes, MaxCanvasOperations)
	out.WriteString("export type ModelSelection = { kind: \"logical\"; logicalModelId: string; channelId?: never; modelKey?: never } | { kind: \"channel\"; channelId: string; modelKey: string; logicalModelId?: never };\n\n")
	for _, typ := range []reflect.Type{reflect.TypeOf(Options{}), reflect.TypeOf(ReferenceBinding{}), reflect.TypeOf(GenerationSpec{})} {
		fmt.Fprintf(&out, "export type %s = {\n", typ.Name())
		for i := 0; i < typ.NumField(); i++ {
			field := typ.Field(i)
			parts := strings.Split(field.Tag.Get("json"), ",")
			optional := ""
			if len(parts) > 1 && parts[1] == "omitempty" {
				optional = "?"
			}
			valueType := tsType(field.Type)
			if values := field.Tag.Get("enum"); values != "" {
				quoted := []string{}
				for _, value := range strings.Split(values, ",") {
					quoted = append(quoted, fmt.Sprintf("%q", value))
				}
				valueType = strings.Join(quoted, " | ")
			}
			fmt.Fprintf(&out, "    %s%s: %s;\n", parts[0], optional, valueType)
		}
		out.WriteString("};\n\n")
	}
	fields := []map[string]any{}
	typ := reflect.TypeOf(Options{})
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		fields = append(fields, map[string]any{"name": strings.Split(field.Tag.Get("json"), ",")[0], "node": field.Tag.Get("node"), "task": field.Tag.Get("task"), "kind": tsType(field.Type), "modes": strings.Split(field.Tag.Get("modes"), ",")})
	}
	encoded, _ := json.MarshalIndent(fields, "", "    ")
	fmt.Fprintf(&out, "export const GENERATION_OPTION_FIELDS = %s as const;\n", encoded)
	return out.String()
}

func tsType(typ reflect.Type) string {
	switch typ.Kind() {
	case reflect.Pointer:
		return tsType(typ.Elem())
	case reflect.Slice:
		return tsType(typ.Elem()) + "[]"
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int:
		return "number"
	default:
		return typ.Name()
	}
}
