// 来源：火山引擎《音色列表》中的「豆包语音合成模型1.0」。
// seed-audio-1.0 对应资源 seed-tts-1.0，只能使用这一代音色，不能混入 2.0。
// 文档里同一个音色编号会按语种重复出现，下拉框按音色编号去重。

export type DoubaoAudioVoiceOption = {
    scene: string;
    value: string;
    label: string;
    language: string;
};

export const doubaoDefaultAudioVoice = "zh_female_shuangkuaisisi_moon_bigtts";

export const doubaoAudioVoiceOptions: DoubaoAudioVoiceOption[] = [
    { scene: "多情感", value: "zh_male_lengkugege_emo_v2_mars_bigtts", label: "冷酷哥哥", language: "中文" },
    { scene: "多情感", value: "zh_female_tianxinxiaomei_emo_v2_mars_bigtts", label: "甜心小美", language: "中文" },
    { scene: "多情感", value: "zh_male_guangzhoudege_emo_mars_bigtts", label: "广州德哥", language: "中文" },
    { scene: "多情感", value: "zh_male_jingqiangkanye_emo_mars_bigtts", label: "京腔侃爷", language: "中文" },
    { scene: "多情感", value: "zh_female_linjuayi_emo_v2_mars_bigtts", label: "邻居阿姨", language: "中文" },
    { scene: "多情感", value: "zh_male_yourougongzi_emo_v2_mars_bigtts", label: "优柔公子", language: "中文" },
    { scene: "多情感", value: "zh_male_ruyayichen_emo_v2_mars_bigtts", label: "儒雅男友", language: "中文" },
    { scene: "多情感", value: "zh_male_junlangnanyou_emo_v2_mars_bigtts", label: "俊朗男友", language: "中文" },
    { scene: "多情感", value: "zh_male_beijingxiaoye_emo_v2_mars_bigtts", label: "北京小爷", language: "中文" },
    { scene: "多情感", value: "zh_female_roumeinvyou_emo_v2_mars_bigtts", label: "柔美女友", language: "中文" },
    { scene: "多情感", value: "zh_male_yangguangqingnian_emo_v2_mars_bigtts", label: "阳光青年", language: "中文" },
    { scene: "多情感", value: "zh_female_meilinvyou_emo_v2_mars_bigtts", label: "魅力女友", language: "中文" },
    { scene: "多情感", value: "zh_female_shuangkuaisisi_emo_v2_mars_bigtts", label: "爽快思思", language: "中文、英式英语" },
    { scene: "多情感", value: "zh_male_shenyeboke_emo_v2_mars_bigtts", label: "深夜播客", language: "中文" },
    { scene: "多情感", value: "en_female_candice_emo_v2_mars_bigtts", label: "美式英语 · 坎迪丝", language: "美式英语" },
    { scene: "教育场景", value: "zh_female_yingyujiaoyu_mars_bigtts", label: "蒂娜老师", language: "中文、英式英语" },
    { scene: "通用场景", value: "zh_female_qinqienvsheng_moon_bigtts", label: "亲切女声", language: "中文" },
    { scene: "通用场景", value: "zh_male_qingyiyuxuan_mars_bigtts", label: "阳光阿辰", language: "中文" },
    { scene: "通用场景", value: "zh_male_xudong_conversation_wvae_bigtts", label: "快乐小东", language: "中文、美式英语" },
    { scene: "通用场景", value: "en_male_jason_conversation_wvae_bigtts", label: "开朗学长", language: "中文" },
    { scene: "通用场景", value: "zh_female_tianmeitaozi_mars_bigtts", label: "甜美桃子", language: "中文" },
    { scene: "通用场景", value: "zh_female_qingxinnvsheng_mars_bigtts", label: "清新女声", language: "中文" },
    { scene: "通用场景", value: "zh_female_zhixingnvsheng_mars_bigtts", label: "知性女声", language: "中文" },
    { scene: "通用场景", value: "zh_male_qingshuangnanda_mars_bigtts", label: "清爽男大", language: "中文" },
    { scene: "通用场景", value: "zh_female_linjianvhai_moon_bigtts", label: "邻家女孩", language: "中文" },
    { scene: "通用场景", value: "zh_male_yuanboxiaoshu_moon_bigtts", label: "渊博小叔", language: "中文" },
    { scene: "通用场景", value: "zh_male_yangguangqingnian_moon_bigtts", label: "阳光青年", language: "中文" },
    { scene: "通用场景", value: "zh_female_tianmeixiaoyuan_moon_bigtts", label: "甜美小源", language: "中文" },
    { scene: "通用场景", value: "zh_female_qingchezizi_moon_bigtts", label: "清澈梓梓", language: "中文" },
    { scene: "通用场景", value: "zh_male_jieshuoxiaoming_moon_bigtts", label: "解说小明", language: "中文" },
    { scene: "通用场景", value: "zh_female_kailangjiejie_moon_bigtts", label: "开朗姐姐", language: "中文" },
    { scene: "通用场景", value: "zh_male_linjiananhai_moon_bigtts", label: "邻家男孩", language: "中文" },
    { scene: "通用场景", value: "zh_female_tianmeiyueyue_moon_bigtts", label: "甜美悦悦", language: "中文" },
    { scene: "通用场景", value: "zh_female_xinlingjitang_moon_bigtts", label: "心灵鸡汤", language: "中文" },
    { scene: "通用场景", value: "zh_male_wenrouxiaoge_mars_bigtts", label: "温柔小哥", language: "中文" },
    { scene: "通用场景", value: "zh_female_cancan_mars_bigtts", label: "灿灿", language: "中文、美式英语" },
    { scene: "通用场景", value: "zh_female_shuangkuaisisi_moon_bigtts", label: "爽快思思", language: "中文、美式英语" },
    { scene: "通用场景", value: "zh_male_wennuanahu_moon_bigtts", label: "温暖阿虎", language: "中文、美式英语" },
    { scene: "通用场景", value: "zh_male_shaonianzixin_moon_bigtts", label: "少年梓辛", language: "中文、美式英语" },
    { scene: "趣味口音", value: "zh_female_yueyunv_mars_bigtts", label: "粤语小溏", language: "中文" },
    { scene: "趣味口音", value: "zh_male_yuzhouzixuan_moon_bigtts", label: "豫州子轩", language: "河南口音" },
    { scene: "趣味口音", value: "zh_female_daimengchuanmei_moon_bigtts", label: "呆萌川妹", language: "四川口音" },
    { scene: "趣味口音", value: "zh_male_guangxiyuanzhou_moon_bigtts", label: "广西远舟", language: "广西口音" },
    { scene: "趣味口音", value: "zh_male_zhoujielun_emo_v2_mars_bigtts", label: "双节棍小哥", language: "台湾口音" },
    { scene: "趣味口音", value: "zh_female_wanwanxiaohe_moon_bigtts", label: "湾湾小何", language: "台湾口音" },
    { scene: "趣味口音", value: "zh_female_wanqudashu_moon_bigtts", label: "湾区大叔", language: "广东口音" },
    { scene: "趣味口音", value: "zh_male_guozhoudege_moon_bigtts", label: "广州德哥", language: "广东口音" },
    { scene: "趣味口音", value: "zh_male_haoyuxiaoge_moon_bigtts", label: "浩宇小哥", language: "青岛口音" },
    { scene: "趣味口音", value: "zh_male_beijingxiaoye_moon_bigtts", label: "北京小爷", language: "北京口音" },
    { scene: "趣味口音", value: "zh_male_jingqiangkanye_moon_bigtts", label: "京腔侃爷", language: "北京口音、美式英语" },
    { scene: "趣味口音", value: "zh_female_meituojieer_moon_bigtts", label: "妹坨洁儿", language: "长沙口音" },
    { scene: "角色扮演", value: "zh_male_naiqimengwa_mars_bigtts", label: "奶气萌娃", language: "中文" },
    { scene: "角色扮演", value: "zh_female_popo_mars_bigtts", label: "婆婆", language: "中文" },
    { scene: "角色扮演", value: "zh_female_gaolengyujie_moon_bigtts", label: "高冷御姐", language: "中文" },
    { scene: "角色扮演", value: "zh_male_aojiaobazong_moon_bigtts", label: "傲娇霸总", language: "中文" },
    { scene: "角色扮演", value: "zh_female_meilinvyou_moon_bigtts", label: "魅力女友", language: "中文" },
    { scene: "角色扮演", value: "zh_male_shenyeboke_moon_bigtts", label: "深夜播客", language: "中文" },
    { scene: "角色扮演", value: "zh_female_sajiaonvyou_moon_bigtts", label: "柔美女友", language: "中文" },
    { scene: "角色扮演", value: "zh_female_yuanqinvyou_moon_bigtts", label: "撒娇学妹", language: "中文" },
    { scene: "角色扮演", value: "zh_male_dongfanghaoran_moon_bigtts", label: "东方浩然", language: "中文" },
    { scene: "外语音色", value: "en_male_adam_mars_bigtts", label: "美式英语 · 亚当", language: "美式英语" },
    { scene: "外语音色", value: "en_female_amanda_mars_bigtts", label: "美式英语 · 阿曼达", language: "美式英语" },
    { scene: "外语音色", value: "en_male_jackson_mars_bigtts", label: "美式英语 · 杰克逊", language: "美式英语" },
    { scene: "外语音色", value: "en_male_smith_mars_bigtts", label: "英式英语 · 史密斯", language: "英式英语" },
    { scene: "外语音色", value: "en_female_anna_mars_bigtts", label: "英式英语 · 安娜", language: "英式英语" },
    { scene: "外语音色", value: "en_female_sarah_mars_bigtts", label: "澳洲英语 · 萨拉", language: "澳洲英语" },
    { scene: "外语音色", value: "en_male_dryw_mars_bigtts", label: "澳洲英语 · 德鲁", language: "澳洲英语" },
    { scene: "外语音色", value: "multi_male_M100_conversation_wvae_bigtts", label: "西语 · 卢西亚", language: "西语" },
    { scene: "外语音色", value: "multi_zh_male_youyoujunzi_moon_bigtts", label: "日语 · 光", language: "日语" },
    { scene: "外语音色", value: "multi_female_sophie_conversation_wvae_bigtts", label: "日语 · 智美", language: "日语、西语" },
    { scene: "外语音色", value: "multi_male_xudong_conversation_wvae_bigtts", label: "日语 · 正男", language: "日语、西语" },
    { scene: "外语音色", value: "multi_female_maomao_conversation_wvae_bigtts", label: "日语 · 月", language: "日语、西语" },
    { scene: "外语音色", value: "multi_female_gaolengyujie_moon_bigtts", label: "日语 · 朱美", language: "日语" },
    { scene: "外语音色", value: "multi_male_jingqiangkanye_moon_bigtts", label: "日语 · 和音", language: "日语、西语" },
    { scene: "外语音色", value: "multi_female_shuangkuaisisi_moon_bigtts", label: "日语 · 晴子", language: "日语、西语" },
    { scene: "外语音色", value: "multi_male_wanqudashu_moon_bigtts", label: "日语 · 广志", language: "日语、西语" },
    { scene: "视频配音", value: "zh_male_M100_conversation_wvae_bigtts", label: "悠悠君子", language: "中文、美式英语" },
    { scene: "视频配音", value: "zh_female_maomao_conversation_wvae_bigtts", label: "文静毛毛", language: "中文" },
    { scene: "视频配音", value: "zh_female_wenrouxiaoya_moon_bigtts", label: "温柔小雅", language: "中文" },
    { scene: "视频配音", value: "zh_male_tiancaitongsheng_mars_bigtts", label: "天才童声", language: "中文" },
    { scene: "视频配音", value: "zh_male_sunwukong_mars_bigtts", label: "猴哥", language: "中文" },
    { scene: "视频配音", value: "zh_male_xionger_mars_bigtts", label: "熊二", language: "中文" },
    { scene: "视频配音", value: "zh_female_peiqi_mars_bigtts", label: "佩奇猪", language: "中文" },
    { scene: "视频配音", value: "zh_female_wuzetian_mars_bigtts", label: "武则天", language: "中文" },
    { scene: "视频配音", value: "zh_female_gujie_mars_bigtts", label: "顾姐", language: "中文" },
    { scene: "视频配音", value: "zh_female_yingtaowanzi_mars_bigtts", label: "樱桃丸子", language: "中文" },
    { scene: "视频配音", value: "zh_male_chunhui_mars_bigtts", label: "广告解说", language: "中文" },
    { scene: "视频配音", value: "zh_female_shaoergushi_mars_bigtts", label: "少儿故事", language: "中文" },
    { scene: "视频配音", value: "zh_male_silang_mars_bigtts", label: "四郎", language: "中文" },
    { scene: "视频配音", value: "zh_female_qiaopinvsheng_mars_bigtts", label: "俏皮女声", language: "中文" },
    { scene: "视频配音", value: "zh_male_lanxiaoyang_mars_bigtts", label: "懒音绵宝", language: "中文" },
    { scene: "视频配音", value: "zh_male_dongmanhaimian_mars_bigtts", label: "亮嗓萌仔", language: "中文" },
    { scene: "视频配音", value: "zh_female_jitangmeimei_mars_bigtts", label: "鸡汤妹妹", language: "中文、美式英语" },
    { scene: "视频配音", value: "zh_female_tiexinnvsheng_mars_bigtts", label: "贴心女声", language: "中文、美式英语" },
    { scene: "视频配音", value: "zh_female_mengyatou_mars_bigtts", label: "萌丫头", language: "中文、美式英语" },
    { scene: "有声阅读", value: "zh_male_changtianyi_mars_bigtts", label: "悬疑解说", language: "中文" },
    { scene: "有声阅读", value: "zh_male_ruyaqingnian_mars_bigtts", label: "儒雅青年", language: "中文" },
    { scene: "有声阅读", value: "zh_male_baqiqingshu_mars_bigtts", label: "霸气青叔", language: "中文" },
    { scene: "有声阅读", value: "zh_male_qingcang_mars_bigtts", label: "擎苍", language: "中文" },
    { scene: "有声阅读", value: "zh_male_yangguangqingnian_mars_bigtts", label: "活力小哥", language: "中文" },
    { scene: "有声阅读", value: "zh_female_gufengshaoyu_mars_bigtts", label: "古风少御", language: "中文" },
    { scene: "有声阅读", value: "zh_female_wenroushunv_mars_bigtts", label: "温柔淑女", language: "中文" },
    { scene: "有声阅读", value: "zh_male_fanjuanqingnian_mars_bigtts", label: "反卷青年", language: "中文" },
];
