import type { SkillCategory, WorkbenchSkill } from "../types/skill-contract";

export const BUILTIN_CATEGORIES: SkillCategory[] = [
    { id: "recommend", name: "推荐", iconName: "recommend", order: 0 },
    { id: "portrait", name: "人物", iconName: "portrait", order: 1 },
    { id: "ecommerce", name: "商品", iconName: "ecommerce", order: 2 },
    { id: "spatial", name: "空间", iconName: "spatial", order: 3 },
    { id: "cinema", name: "影视", iconName: "cinema", order: 4 },
    { id: "oriental", name: "国风", iconName: "oriental", order: 5 },
    { id: "social", name: "社媒", iconName: "social", order: 6 },
    { id: "enhance", name: "增强", iconName: "enhance", order: 7 },
];

export const BUILTIN_SKILLS: WorkbenchSkill[] = [
    {
        id: "face-3views",
        categoryId: "portrait",
        name: "脸部三视图",
        subtitle: "生成正脸、侧脸、半侧脸参考",
        description: "生成正脸、侧脸、半侧脸参考",
        isRecommended: true,
        badgeIcon: "smile",
        order: 1,
        defaultCount: 1,
        maxFiles: 3,
        avatarUrl: "/images/skills/face-3views-avatar.webp",
        uploadSlots: [
            {
                id: "face",
                label: "添加人脸",
                iconType: "face",
                semanticTag: "人脸",
                description: "上传清晰正脸参考图",
            },
        ],
        placeholder: "上传清晰人脸图，可补充角色气质、表情或写实程度。",
        instructions: "严格以@图片1为人物面孔原型，生成同套发型与骨相的高清正脸（Front view 0°）、正侧脸（Profile view 90°）、半侧脸（Three-quarter view 45°）三视角标准参考图。各视角水平视平线对齐，五官比例与骨骼结构严格保持1:1一致。中性灰调背景，棚拍平光均匀打光。",
        avoid: ["面部扭曲", "五官不对齐", "左右眼大小不一", "非同一个人", "过度磨皮塑料感"],
        showcaseTitle: "脸部三视图效果示例",
        showcaseSubtitle: "正脸、侧脸、半侧脸多视角美学结构参考",
        showcaseImageUrl: "/images/skills/face-3views.webp",
    },
    {
        id: "face-swap",
        categoryId: "portrait",
        name: "模特换脸",
        subtitle: "一键替换面部与发型",
        description: "一键替换面部与发型",
        isRecommended: true,
        badgeIcon: "image",
        order: 2,
        defaultCount: 1,
        maxFiles: 9,
        avatarUrl: "/images/skills/face-swap-avatar.webp",
        uploadSlots: [
            {
                id: "model",
                label: "添加模特",
                iconType: "model",
                semanticTag: "模特",
                description: "上传待换脸的模特底图",
            },
            {
                id: "face",
                label: "添加人脸",
                iconType: "face",
                semanticTag: "目标人脸",
                description: "上传目标换脸面容与发型参考",
            },
        ],
        placeholder: "可补充表情、妆容、发型细节等要求，例如：自然微笑、淡妆、保留刘海。",
        instructions: "以@图片1为模特身体骨骼、姿势、服饰与环境底图，将@图片2的目标面容与发型高保真置换进模特头部。边缘发丝自然融合，面部光影方向、色温、高光阴影与原环境100%匹配。",
        avoid: ["换脸边缘生硬", "色调不均", "假面感", "脖子色差", "原模特服饰变形"],
        showcaseTitle: "模特换脸效果示例",
        showcaseSubtitle: "创意面部替换与原生光影发型无痕融合",
        showcaseImageUrl: "/images/skills/face-swap.webp",
    },
    {
        id: "product-hero",
        categoryId: "ecommerce",
        name: "商品白底图",
        subtitle: "生成高级白底商品图与多角度资产",
        description: "生成高级白底商品图与多角度资产",
        isRecommended: true,
        badgeIcon: "image",
        order: 3,
        defaultCount: 1,
        maxFiles: 9,
        avatarUrl: "/images/skills/product-hero-avatar.webp",
        uploadSlots: [
            {
                id: "product",
                label: "添加产品",
                iconType: "product",
                semanticTag: "产品",
                description: "上传产品原图或实拍图",
            },
        ],
        placeholder: "可补充拍摄角度、和需要保留的细节等",
        instructions: "以@图片1为原始产品外观，生成纯净无噪点的纯白背景（#FFFFFF）电商主图与三视图静物资产。严格锁定产品材质反射（金属拉丝/哑光塑料/皮革缝线/玻璃透明度），还原真实软阴影与微弱地面倒影。",
        avoid: ["产品商标文字变形", "边缘杂色", "背景不纯白", "结构比例畸变"],
        showcaseTitle: "商品白底图效果示例",
        showcaseSubtitle: "工业级纯净白底电商主图与三维静物资产",
        showcaseImageUrl: "/images/skills/product-hero.webp",
    },
    {
        id: "image-refinement",
        categoryId: "enhance",
        secondaryCategoryIds: ["portrait", "enhance"],
        name: "图片精修",
        subtitle: "修复画质、光影和清晰度",
        description: "修复画质、光影和清晰度",
        isRecommended: true,
        badgeIcon: "sparkles",
        order: 4,
        defaultCount: 1,
        maxFiles: 9,
        avatarUrl: "/images/skills/image-refinement-avatar.webp",
        uploadSlots: [
            {
                id: "target",
                label: "添加产品",
                iconType: "product",
                semanticTag: "待精修图",
                description: "上传需要修复或精修的图片",
            },
        ],
        placeholder: "可补充精修图片的要求，比如瘦脸、美颜等",
        instructions: "以@图片1为基础底图，进行大师级商业画质重塑。大幅提升细节清晰度与锐度，重塑通透的立体高光与暗部层次，消除原图噪点、模糊与粗糙杂色，保持原图主体构图与核心轮廓不变。",
        avoid: ["过度锐化导致光晕", "改变原物形态", "色彩过饱和"],
        showcaseTitle: "图片/美颜精修效果示例",
        showcaseSubtitle: "逆光通透肤质、发丝光晕与质感级美颜",
        showcaseImageUrl: "/images/skills/image-refinement.webp",
    },
    {
        id: "virtual-try-on",
        categoryId: "ecommerce",
        name: "服装上身",
        subtitle: "替换模特身上的服装衣物",
        description: "替换模特身上的服装衣物",
        isRecommended: true,
        badgeIcon: "image",
        order: 5,
        defaultCount: 1,
        maxFiles: 6,
        avatarUrl: "/images/skills/virtual-try-on-avatar.webp",
        uploadSlots: [
            {
                id: "model",
                label: "添加模特",
                iconType: "model",
                semanticTag: "模特",
                description: "上传模特全身或半身图",
            },
            {
                id: "top",
                label: "添加上身/全身装 (可选)",
                iconType: "top",
                optional: true,
                semanticTag: "上身/全身装",
                description: "上传上装、外套或连衣裙白底/平铺图",
            },
            {
                id: "bottom",
                label: "添加下装 (可选)",
                iconType: "bottom",
                optional: true,
                semanticTag: "下装",
                description: "上传裤装或半身裙白底/平铺图",
            },
        ],
        placeholder: "可补充模特姿势、动作、穿搭效果、场景氛围等，例如：自然站立、双手插兜、衣服更宽松一些。",
        instructions: "将@图片2（上装）或@图片3（下装）的版型、面料质感、格纹图案与垂坠感完美穿搭在@图片1的真人模特身上。衣物褶皱必须根据模特当前的肢体关节转折自然延展，领口与袖口严密贴合，保留模特本身的肤色、发丝与面部特征。",
        avoid: ["衣物版型变形", "面料印花错位", "模特面孔变化", "肢体穿模"],
        showcaseTitle: "服装上身效果示例",
        showcaseSubtitle: "高级街头服饰 Lookbook 模特上身实拍",
        showcaseImageUrl: "/images/skills/virtual-try-on.webp",
    },
    {
        id: "product-lifestyle",
        categoryId: "ecommerce",
        name: "商品使用",
        subtitle: "生成真人试用与使用场景",
        description: "生成真人试用与使用场景",
        isRecommended: true,
        badgeIcon: "shopping-bag",
        order: 6,
        defaultCount: 1,
        maxFiles: 9,
        avatarUrl: "/images/skills/product-lifestyle-avatar.webp",
        uploadSlots: [
            {
                id: "model",
                label: "添加模特",
                iconType: "model",
                semanticTag: "模特",
                description: "上传模特人物图",
            },
            {
                id: "product",
                label: "添加商品",
                iconType: "product",
                semanticTag: "商品",
                description: "上传商品单品图",
            },
        ],
        placeholder: "上传产品与人物参考图，可补充使用动作、场景和构图。",
        instructions: "将@图片2的产品自然融入@图片1模特的生活化场景中。无论是手提、单肩背戴或手持交互，手部握持力道与重力下垂需真实自然，产品尺寸比例严密贴合人体工学，环境阳光与背景虚化烘托高级生活方式感。",
        avoid: ["产品LOGO形变", "手部手指畸形", "握持悬空", "产品尺寸过大或过小"],
        showcaseTitle: "商品使用效果示例",
        showcaseSubtitle: "真实自然光手持饮品街拍生活场景",
        showcaseImageUrl: "/images/skills/product-lifestyle.webp",
    },
    {
        id: "character-4views",
        categoryId: "portrait",
        name: "人物四视图",
        subtitle: "生成全身三视角与脸部特写",
        description: "生成全身三视角与脸部特写",
        badgeIcon: "image",
        order: 7,
        defaultCount: 1,
        maxFiles: 5,
        avatarUrl: "/images/skills/character-4views-avatar.webp",
        uploadSlots: [
            {
                id: "model",
                label: "添加模特",
                iconType: "model",
                semanticTag: "模特",
                description: "上传包含脸部和身形的人物图",
            },
        ],
        placeholder: "上传包含脸部和身形的人物图，可补充穿搭与人物气质。",
        instructions: "以@图片1为角色原型，标准生成4格角色设定表：正面全身（Front Full-body）、正侧面全身（Side Full-body）、背面全身（Back Full-body）、面部高清大特写（Face Close-up）。各全身视角肩高、腰线、脚跟水平基准完全锁定，服装细节前后呼应。",
        avoid: ["各视角身材比例不一", "背面发型不匹配", "肢体畸变", "不同角度服装不一致"],
        showcaseTitle: "人物四视图效果示例",
        showcaseSubtitle: "正背侧三视角与局部特写工业级角色设定表",
        showcaseImageUrl: "/images/skills/character-4views.webp",
    },
    {
        id: "face-fusion",
        categoryId: "portrait",
        name: "人脸融合",
        subtitle: "融合两张人脸生成全新虚拟头像资产",
        description: "融合两张人脸生成全新虚拟头像资产",
        badgeIcon: "image",
        order: 8,
        defaultCount: 1,
        maxFiles: 9,
        avatarUrl: "/images/skills/face-fusion-avatar.webp",
        uploadSlots: [
            {
                id: "face1",
                label: "添加人脸1",
                iconType: "face",
                semanticTag: "人脸1",
                description: "上传第一张参考面孔",
            },
            {
                id: "face2",
                label: "添加人脸2",
                iconType: "face",
                semanticTag: "人脸2",
                description: "上传第二张参考面孔",
            },
        ],
        placeholder: "可补充融合比例、年龄感、气质、表情等要求，例如：更偏向图1、约25岁、清冷感、自然微笑。",
        instructions: "深度融合@图片1与@图片2的五官拓扑结构、眼鼻比例与骨骼轮廓，生成具有两者融合特征但极具辨识度的全新虚拟面部资产。保留高清晰皮肤肌理与自然神韵。",
        avoid: ["五官拼凑生硬", "重影假死", "面部比例失调"],
        showcaseTitle: "人脸融合效果示例",
        showcaseSubtitle: "多面容骨相特征融合与艺术人像拼贴",
        showcaseImageUrl: "/images/skills/face-fusion.webp",
    },
    {
        id: "clothing-redesign",
        categoryId: "ecommerce",
        name: "服装改款",
        subtitle: "替换服装的面料、印花等",
        description: "替换服装的面料、印花等",
        badgeIcon: "sparkles",
        order: 9,
        defaultCount: 1,
        maxFiles: 9,
        avatarUrl: "/images/skills/clothing-redesign-avatar.webp",
        uploadSlots: [
            {
                id: "clothing",
                label: "添加服装",
                iconType: "top",
                semanticTag: "原版服装",
                description: "上传需要改款的版型底图",
            },
            {
                id: "fabric",
                label: "添加面料 (可选)",
                iconType: "fabric",
                optional: true,
                semanticTag: "参考面料",
                description: "上传面料材质样板小样",
            },
            {
                id: "print",
                label: "添加印花 (可选)",
                iconType: "print",
                optional: true,
                semanticTag: "参考印花",
                description: "上传表面图案与印花图案",
            },
        ],
        placeholder: "可补充面料描述，印花位置等描述",
        instructions: "以@图片1的原版服装版型与剪裁为骨架，参考@图片2的面料纤维结构或@图片3的图案印花，重新渲染不同材质（如羊毛针织、皮革、雪纺）与配色花纹的衍生系列新款。",
        avoid: ["破坏原衣服版型结构", "印花扭曲变形", "质感粗糙模糊"],
        showcaseTitle: "服装改款效果示例",
        showcaseSubtitle: "同款廓形探索不同文化纹样与面料改款",
        showcaseImageUrl: "/images/skills/clothing-redesign.webp",
    },
    {
        id: "character-staging",
        categoryId: "cinema",
        secondaryCategoryIds: ["cinema"],
        name: "人物入景",
        subtitle: "替换模特图背景",
        description: "替换模特图背景",
        isRecommended: true,
        badgeIcon: "image",
        order: 10,
        defaultCount: 1,
        maxFiles: 9,
        avatarUrl: "/images/skills/character-staging-avatar.webp",
        uploadSlots: [
            {
                id: "model",
                label: "添加模特",
                iconType: "model",
                semanticTag: "模特人物",
                description: "上传待抠像的模特原片",
            },
            {
                id: "background",
                label: "添加背景",
                iconType: "background",
                semanticTag: "目标背景",
                description: "上传期望置入的场景底图",
            },
        ],
        placeholder: "可补充人物姿势，位置等描述",
        instructions: "将@图片1的模特主体完整抠出，精细保留半透明发丝与服饰边缘，自然置于@图片2的目标背景中。计算背景的光源角度与色温，在模特身上生成对应的环境补光与地面接触阴影。",
        avoid: ["白边杂色", "透视不匹配", "光影逆向", "人悬浮在空中"],
        showcaseTitle: "人物入景效果示例",
        showcaseSubtitle: "晨光微尘环境光影与人物自然融入实景",
        showcaseImageUrl: "/images/skills/character-staging.webp",
    },
    {
        id: "character-realism",
        categoryId: "enhance",
        secondaryCategoryIds: ["portrait", "enhance"],
        name: "人物真人感",
        subtitle: "AI虚拟人添加真实感",
        description: "AI虚拟人添加真实感",
        badgeIcon: "image",
        order: 11,
        defaultCount: 1,
        maxFiles: 9,
        avatarUrl: "/images/skills/character-realism-avatar.webp",
        uploadSlots: [
            {
                id: "model",
                label: "添加模特",
                iconType: "model",
                semanticTag: "待优化虚拟人",
                description: "上传需要去除AI塑料感的虚拟人图",
            },
        ],
        placeholder: "上传待优化的人像，可说明需要加强的脸部、手部、发丝或光影。",
        instructions: "以@图片1为输入，针对AI生成人像常见的蜡像感、塑料反光与眼神空洞进行终极真实化重构。重建真实人体皮肤微孔、细微绒毛、真实虹膜反光与发丝空气感。",
        avoid: ["面部结构改变", "面孔换人", "油腻高光"],
        showcaseTitle: "人物真人感效果示例",
        showcaseSubtitle: "消除塑料感、iPhone 随手抓拍真实生活质感",
        showcaseImageUrl: "/images/skills/character-realism.webp",
    },
    {
        id: "exploded-view",
        categoryId: "ecommerce",
        name: "3D拆解爆炸图",
        subtitle: "生成产品内部精密结构与组件拆解",
        description: "生成产品内部精密结构与组件拆解",
        badgeIcon: "image",
        order: 12,
        defaultCount: 1,
        maxFiles: 3,
        avatarUrl: "/images/skills/exploded-view-avatar.webp",
        uploadSlots: [
            {
                id: "product",
                label: "添加产品",
                iconType: "product",
                semanticTag: "产品",
                description: "上传需展示内部结构的产品原图",
            },
        ],
        placeholder: "上传工业产品或数码配件，可说明爆炸图轴测角度、组件拆解层数与内部零件标注。",
        instructions: "以@图片1为基础产品模型，生成专业工业级3D分层爆炸拆解图（Exploded View）。沿45度轴测投影展开精密内部结构，展示内部机械零部件、电路板、电池模组与外壳卡扣。各组件保持正确的空间装配次序与悬浮间距，纯净浅灰或白色工业背景，锐利光影与精细五金质感。",
        avoid: ["组件结构混乱", "零件形态扭曲", "透视轴线不一致", "零件穿模"],
        showcaseTitle: "3D拆解爆炸图效果示例",
        showcaseSubtitle: "精密电子组件悬浮拆解与机械透视结构",
        showcaseImageUrl: "/images/skills/exploded-view.webp",
    },
    {
        id: "detail-8pack",
        categoryId: "ecommerce",
        name: "商详套图全案",
        subtitle: "首图/卖点/场景/成分等8大细分",
        description: "首图/卖点/场景/成分等8大细分",
        badgeIcon: "shopping-bag",
        order: 13,
        defaultCount: 8,
        maxFiles: 5,
        avatarUrl: "/images/skills/detail-8pack-avatar.webp",
        uploadSlots: [
            {
                id: "product",
                label: "上传商品图 (最多5张)",
                iconType: "product",
                maxCount: 5,
                semanticTag: "商品主体",
                description: "上传商品白底或多角度实拍图",
            },
        ],
        placeholder: "可补充卖点方向、目标受众、使用场景、希望突出的核心功能与品牌视觉风格...",
        instructions: "以@图片为商品主体，生成电商高转化详情页成套视觉物料（8大黄金版块：首图主视觉、功效卖点图、真实使用场景图、成分原料图、材质细节特写图、内部功能结构图、痛点对比图、包装到手图）。构图比例考究，预留高保真排版安全区，光影质感与商品实物高度一致。",
        avoid: ["商品外观形变", "虚假卖点陈列", "文字排版重叠", "光影混乱"],
        showcaseTitle: "商详套图全案效果示例",
        showcaseSubtitle: "卖点场景解析与国际化电商 A+ 详图全案",
        showcaseImageUrl: "/images/skills/detail-8pack.webp",
    },
    {
        id: "bare-to-renovated",
        categoryId: "spatial",
        name: "毛坯房改精装",
        subtitle: "毛坯与破旧空间焕新渲染",
        description: "毛坯与破旧空间焕新渲染",
        isRecommended: true,
        badgeIcon: "image",
        order: 14,
        defaultCount: 1,
        maxFiles: 3,
        avatarUrl: "/images/skills/bare-to-renovated-avatar.webp",
        uploadSlots: [
            {
                id: "bare_room",
                label: "添加毛坯实拍图",
                iconType: "room",
                semanticTag: "毛坯空间",
                description: "上传毛坯房或旧房实拍图",
            },
            {
                id: "style_ref",
                label: "添加风格参考 (可选)",
                iconType: "background",
                optional: true,
                semanticTag: "装修风格",
                description: "上传目标软装风格样板参考",
            },
        ],
        placeholder: "上传毛坯或旧房实拍，可补充装修风格（如法式轻奢、北欧奶油风、现代极简）、主色调及采光要求。",
        instructions: "以@图片1为原始房屋空间结构骨架，严格保留建筑承重梁柱、门窗采光位置与透视基准线。参考@图片2或指定风格进行全屋精装重塑，铺设高档地板、艺术吊顶与无主灯氛围照明，置入配套家具软装，生成落地级实景精装修摄影大片。",
        avoid: ["随意改动承重结构", "门窗位置错乱", "空间比例失调", "透视畸变"],
        showcaseTitle: "毛坯房改精装效果示例",
        showcaseSubtitle: "空间结构复原、室内软装与旧房焕新渲染",
        showcaseImageUrl: "/images/skills/bare-to-renovated.webp",
    },
    {
        id: "day-night-lighting",
        categoryId: "spatial",
        name: "昼夜光影切换",
        subtitle: "自然日光与氛围暖光转换",
        description: "自然日光与氛围暖光转换",
        badgeIcon: "image",
        order: 15,
        defaultCount: 1,
        maxFiles: 2,
        avatarUrl: "/images/skills/day-night-lighting-avatar.webp",
        uploadSlots: [
            {
                id: "room",
                label: "添加空间原图",
                iconType: "room",
                semanticTag: "空间原图",
                description: "上传室内日间或夜间原图",
            },
        ],
        placeholder: "上传白天或夜间室内图，说明需要转换的光照效果（如白天通透日光、黄昏落日余晖、夜间温馨壁灯与氛围灯带）。",
        instructions: "以@图片1为空间硬装与软装基准，保持家具陈设与视角完全不动，精准重塑空间光源与色温。若转为夜景，关闭窗外自然日光，开启室内吊灯、嵌入式筒灯与漫反射暗藏灯带，营造温暖静谧的家居夜间氛围。",
        avoid: ["改变家具陈列", "光影逆向错乱", "局部死黑无细节"],
        showcaseTitle: "昼夜光影切换效果示例",
        showcaseSubtitle: "晨曦日光倾泻与室内空间自然光影转换",
        showcaseImageUrl: "/images/skills/day-night-lighting.webp",
    },
    {
        id: "furniture-in-situ",
        categoryId: "spatial",
        name: "家具白底入室",
        subtitle: "单品家具自动融入样板间",
        description: "单品家具自动融入样板间",
        isRecommended: true,
        badgeIcon: "image",
        order: 16,
        defaultCount: 1,
        maxFiles: 3,
        avatarUrl: "/images/skills/furniture-in-situ-avatar.webp",
        uploadSlots: [
            {
                id: "furniture",
                label: "添加家具白底图",
                iconType: "furniture",
                semanticTag: "家具单品",
                description: "上传沙发、桌椅或柜体白底图",
            },
            {
                id: "room",
                label: "添加目标房间场景 (可选)",
                iconType: "room",
                optional: true,
                semanticTag: "目标房间",
                description: "上传放置的目标室内场景图",
            },
        ],
        placeholder: "上传家具产品图，可补充希望置入的房间类型（如北欧风客厅、极简卧室）、摆放位置及搭配绿植地毯。",
        instructions: "将@图片1中的家具单品（沙发/餐桌椅/茶几/床品）完美置入高品质现代样板间中。100%锁定该家具的造型几何、框架比例、五金细节与面料纹理。在家具与地面、墙面接触处生成精确的物理接触阴影（Contact Shadow）与环境光遮蔽（AO），与空间透视严丝合缝。",
        avoid: ["家具形变缩放失真", "悬浮无投影", "透视与地面不合", "面料反光异常"],
        showcaseTitle: "家具白底入室效果示例",
        showcaseSubtitle: "概念单品家具三维置入现代室内实景样板间",
        showcaseImageUrl: "/images/skills/furniture-in-situ.webp",
    },
    {
        id: "finish-swap",
        categoryId: "spatial",
        name: "面料木色换款",
        subtitle: "换皮、换布、换木纹不改造型",
        description: "换皮、换布、换木纹不改造型",
        badgeIcon: "sparkles",
        order: 17,
        defaultCount: 1,
        maxFiles: 3,
        avatarUrl: "/images/skills/finish-swap-avatar.webp",
        uploadSlots: [
            {
                id: "furniture",
                label: "添加原家具图",
                iconType: "furniture",
                semanticTag: "原家具",
                description: "上传待换款的家具底图",
            },
            {
                id: "material",
                label: "添加面料/木色小样",
                iconType: "fabric",
                semanticTag: "参考材质",
                description: "上传目标面料、皮革或木饰面小样",
            },
        ],
        placeholder: "保持家具骨架与版型不变，将包覆面料替换为参考面料小样，可说明材质光泽与缝线细节。",
        instructions: "以@图片1的家具造型结构与骨架轮廓为基准，将外表面材料替换为@图片2所示的面料材质、皮革纹理或木纹漆面。精准贴合曲面包裹转折，保留原本的缝线工艺与拉扣细节，光泽反光符合真实物理属性。",
        avoid: ["骨架结构变形", "纹理拉伸模糊", "缝线缺失"],
        showcaseTitle: "面料木色换款效果示例",
        showcaseSubtitle: "保持家具单品结构不变、一键替换材质与木纹",
        showcaseImageUrl: "/images/skills/finish-swap.webp",
    },
    {
        id: "tile-flooring",
        categoryId: "spatial",
        name: "地墙砖全屋铺贴",
        subtitle: "单片建材大面积铺设实景效果",
        description: "单片建材大面积铺设实景效果",
        badgeIcon: "image",
        order: 18,
        defaultCount: 1,
        maxFiles: 3,
        avatarUrl: "/images/skills/tile-flooring-avatar.webp",
        uploadSlots: [
            {
                id: "tile",
                label: "添加单片瓷砖/地板",
                iconType: "tile",
                semanticTag: "单片建材",
                description: "上传瓷砖或地板单片纹理图",
            },
            {
                id: "room",
                label: "添加目标空间图 (可选)",
                iconType: "room",
                optional: true,
                semanticTag: "目标空间",
                description: "上传待铺装的房间或毛坯实景",
            },
        ],
        placeholder: "上传单片瓷砖或地板小样，可说明铺贴工艺（如鱼骨拼/人字拼/错位对缝）、美缝宽度及整体空间风格。",
        instructions: "将@图片1的单片建材纹样进行无缝物理平铺，真实渲染在室内空间的地面或背景墙上。严格遵循[工字对缝/鱼骨拼贴/密缝铺贴]标准，砖缝平直且带真实填缝剂凹陷感。纹理随视角产生逼真的远近透视缩放与地表光影漫反射。",
        avoid: ["砖缝弯曲不直", "机械贴图假平铺", "失去透视比例", "反射过曝死白"],
        showcaseTitle: "地墙砖全屋铺贴效果示例",
        showcaseSubtitle: "恢弘大理石与通体瓷砖大面积实景铺设效果",
        showcaseImageUrl: "/images/skills/tile-flooring.webp",
    },
    {
        id: "material-macro-texture",
        categoryId: "spatial",
        name: "材质微距特写",
        subtitle: "岩板/大理石/微水泥质感大片",
        description: "岩板/大理石/微水泥质感大片",
        badgeIcon: "sparkles",
        order: 19,
        defaultCount: 1,
        maxFiles: 2,
        avatarUrl: "/images/skills/material-macro-texture-avatar.webp",
        uploadSlots: [
            {
                id: "material",
                label: "添加材质样板图",
                iconType: "material",
                semanticTag: "材质样板",
                description: "上传岩板、木皮或涂料样板",
            },
        ],
        placeholder: "上传建材样板，可说明表面处理工艺（如哑光磨砂/高光抛釉/皮革纹/拉丝五金）与侧光角度。",
        instructions: "以@图片1为样品底图，生成工业级建材表面微距特写大片（Material Macro Texture）。采用侧向硬掠射光（Raking Light）擦过表面，极细致刻画岩板结晶微粒、天然大理石裂隙、木材导管微孔或金属拉丝倒角，呈现顶级物理触感与材质景深。",
        avoid: ["表面塑料感", "纹理模糊失真", "光线平淡缺乏凹凸起伏"],
        showcaseTitle: "材质微距特写效果示例",
        showcaseSubtitle: "毫厘级刺绣丝线微距与浮雕工艺肌理大片",
        showcaseImageUrl: "/images/skills/material-macro-texture.webp",
    },
    {
        id: "cinematic-storyboard",
        categoryId: "cinema",
        name: "故事叙事关键帧",
        subtitle: "高戏剧张力电影感构图",
        description: "高戏剧张力电影感构图",
        badgeIcon: "image",
        order: 20,
        defaultCount: 1,
        maxFiles: 3,
        avatarUrl: "/images/skills/cinematic-storyboard-avatar.webp",
        uploadSlots: [
            {
                id: "character",
                label: "添加角色立绘",
                iconType: "character",
                semanticTag: "角色主体",
                description: "上传主要人物角色立绘",
            },
            {
                id: "scene",
                label: "添加场景底图 (可选)",
                iconType: "background",
                optional: true,
                semanticTag: "故事场景",
                description: "上传情节发生的场景底图",
            },
        ],
        placeholder: "可补充剧情冲突、人物情绪（愤怒/绝望/深情）、镜头机位（俯拍/仰拍/过肩镜头）与影视色调。",
        instructions: "以@图片1的角色特征为核心，生成极具情绪张力与戏剧冲突的电影分镜画面（Cinematic Narrative Frame）。运用经典好莱坞三点布光与高对比度侧光，构图遵循三分法则或过肩视线引导（OTS），营造强烈的故事悬念与电影胶片颗粒质感。",
        avoid: ["表情僵硬无情绪", "机位呆板平视", "光影平淡无冲突", "画面缺乏纵深"],
        showcaseTitle: "故事叙事关键帧效果示例",
        showcaseSubtitle: "强戏剧张力叙事连贯电影分镜故事画格",
        showcaseImageUrl: "/images/skills/cinematic-storyboard.webp",
    },
    {
        id: "cinemascope-frame",
        categoryId: "cinema",
        name: "宽银幕 2.39:1 构图",
        subtitle: "变形宽银幕胶片质感与光晕",
        description: "变形宽银幕胶片质感与光晕",
        badgeIcon: "image",
        order: 21,
        defaultCount: 1,
        maxFiles: 2,
        avatarUrl: "/images/skills/cinemascope-frame-avatar.webp",
        uploadSlots: [
            {
                id: "source",
                label: "添加核心画面/角色",
                iconType: "character",
                semanticTag: "分镜主体",
                description: "上传宽银幕镜头的主体素材",
            },
        ],
        placeholder: "可补充电影风格（科幻赛博/谍战悬疑/史诗奇幻）、镜头焦段（如35mm变形宽银幕镜头）与光晕效果。",
        instructions: "生成标准的 2.39:1 Anamorphic 电影宽银幕视觉画面。呈现标志性的变形宽银幕水平条形蓝色光晕（Streak Flare）、椭圆形失焦光斑（Oval Bokeh）与边缘微弱桶形畸变，具备深邃的色调分离与好莱坞电影工业级质感。",
        avoid: ["画面被拉伸变形", "画面上下黑边比例错误", "色彩发灰无层次"],
        showcaseTitle: "宽银幕 2.39:1 构图效果示例",
        showcaseSubtitle: "2.39:1 变形宽银幕胶片大画幅光影构图",
        showcaseImageUrl: "/images/skills/cinemascope-frame.webp",
    },
    {
        id: "dynasty-costume",
        categoryId: "oriental",
        name: "朝代服饰考究",
        subtitle: "唐宋明正统形制与纹样复刻",
        description: "唐宋明正统形制与纹样复刻",
        isRecommended: true,
        badgeIcon: "sparkles",
        order: 22,
        defaultCount: 1,
        maxFiles: 3,
        avatarUrl: "/images/skills/dynasty-costume-avatar.webp",
        uploadSlots: [
            {
                id: "model",
                label: "添加人物参考",
                iconType: "model",
                semanticTag: "人物原型",
                description: "上传人物面孔或体态底图",
            },
            {
                id: "pattern",
                label: "添加纹样小样 (可选)",
                iconType: "craft",
                optional: true,
                semanticTag: "历史纹样",
                description: "上传织金、刺绣或传统纹样",
            },
        ],
        placeholder: "指定具体历史朝代（如盛唐、大宋、大明），补充身形体态、发髻冠饰、配饰（禁步/香囊）与妆容细节。",
        instructions: "严谨考究中国古代特定朝代服饰制式（唐代齐胸襦裙/披帛、宋代褙子/抹胸、明代马面裙/织金飞鱼服/补服）。严格还原传统丝绸、织锦、暗花缎质感与传统发髻冠饰，五官妆容契合古典美学（花钿/斜红/面靥），坚决杜绝影视化廉价影楼风与现代违和剪裁。",
        avoid: ["朝代制度穿帮", "现代拉链纽扣", "影楼化雪纺廉价感", "日韩服饰元素混淆"],
        showcaseTitle: "朝代服饰考究效果示例",
        showcaseSubtitle: "传统正统汉服红妆形制与古典刺绣纹样",
        showcaseImageUrl: "/images/skills/dynasty-costume.webp",
    },
    {
        id: "intangible-craft",
        categoryId: "oriental",
        name: "非遗工艺特写",
        subtitle: "掐丝珐琅、螺钿镶嵌与苏绣微距",
        description: "掐丝珐琅、螺钿镶嵌与苏绣微距",
        badgeIcon: "sparkles",
        order: 23,
        defaultCount: 1,
        maxFiles: 2,
        avatarUrl: "/images/skills/intangible-craft-avatar.webp",
        uploadSlots: [
            {
                id: "craft",
                label: "添加工艺器物/小样",
                iconType: "craft",
                semanticTag: "非遗器物",
                description: "上传工艺品或局部纹样图",
            },
        ],
        placeholder: "指定非遗传统工艺门类（如景泰蓝掐丝珐琅、大漆螺钿、苏绣顾绣、南京云锦、花丝镶嵌）与微距细节。",
        instructions: "生成中国非物质文化遗产工艺美术级微距特写。以@图片1为基础，极度细致刻画金属掐丝的铜线反光、螺钿天然七彩贝壳光泽、云锦孔雀羽线交织立体感与刺绣蚕丝光泽。光影柔润内敛，展现东方传统匠作的极致繁复与典雅神韵。",
        avoid: ["机印粗糙噪点", "纹样断线变形", "反光塑料感", "材质质感不清晰"],
        showcaseTitle: "非遗工艺特写效果示例",
        showcaseSubtitle: "景德镇青花窑变与非遗手工艺全流程图谱",
        showcaseImageUrl: "/images/skills/intangible-craft.webp",
    },
    {
        id: "ink-wash-scroll",
        categoryId: "oriental",
        name: "古典水墨长卷",
        subtitle: "青绿山水与金碧水墨晕染",
        description: "青绿山水与金碧水墨晕染",
        badgeIcon: "image",
        order: 24,
        defaultCount: 1,
        maxFiles: 2,
        avatarUrl: "/images/skills/ink-wash-scroll-avatar.webp",
        uploadSlots: [
            {
                id: "subject",
                label: "添加主体/草图",
                iconType: "background",
                semanticTag: "水墨构图",
                description: "上传山水、花鸟或景物草图",
            },
        ],
        placeholder: "可补充画派风格（如青绿山水、大写意、米点皴、工笔界画）、题跋留白与传统国画矿物色（石青/石绿/朱砂）。",
        instructions: "以中国传统水墨画为艺术语言，呈现生宣纸浸润晕染、焦浓重淡清五色墨韵与精妙留白气韵。构图呈现散点透视与游历意境，山石皴法自然有力，矿物颜料沉着斑驳，具备宋元古典文人画的萧散苍茫骨格。",
        avoid: ["西洋油画笔触", "电脑渐变色生硬", "缺乏水墨浓淡干湿层次", "无留白死板满铺"],
        showcaseTitle: "古典水墨长卷效果示例",
        showcaseSubtitle: "气势磅礴宋代青绿金碧水墨千里江山长卷",
        showcaseImageUrl: "/images/skills/ink-wash-scroll.webp",
    },
    {
        id: "redbook-seed",
        categoryId: "social",
        name: "小红书种草图",
        subtitle: "高饱和高明度抓眼球封面",
        description: "高饱和高明度抓眼球封面",
        isRecommended: true,
        badgeIcon: "sparkles",
        order: 25,
        defaultCount: 1,
        maxFiles: 3,
        avatarUrl: "/images/skills/redbook-seed-avatar.webp",
        uploadSlots: [
            {
                id: "product",
                label: "添加种草单品",
                iconType: "product",
                semanticTag: "种草单品",
                description: "上传美妆、穿搭或生活单品图",
            },
            {
                id: "scene",
                label: "添加参考背景 (可选)",
                iconType: "background",
                optional: true,
                semanticTag: "种草场景",
                description: "上传生活化背景参考图",
            },
        ],
        placeholder: "可补充生活场景（如周末咖啡馆、阳光卧室桌面、野餐草地）、色调氛围（韩系奶油/日杂通透/冷白皮）与摆拍道具。",
        instructions: "以@图片1为种草核心，生成符合小红书爆款审美的高赞视觉大片。采用明亮通透的自然光摄影，色彩鲜活明朗，画面构图富有日常呼吸感与精致生活方式氛围，上方或侧边自发留出适量视觉空间便于后续添加吸睛大字标签。",
        avoid: ["影棚摆拍死板感", "色调暗沉压抑", "主体被杂物遮挡", "AI假人感"],
        showcaseTitle: "小红书种草图效果示例",
        showcaseSubtitle: "爆款 3D 浮雕交互卡片与抓眼球封面视觉",
        showcaseImageUrl: "/images/skills/redbook-seed.webp",
    },
    {
        id: "buyer-show-ugc",
        categoryId: "social",
        name: "真实买家秀随拍",
        subtitle: "去影棚化自然光随手拍",
        description: "去影棚化自然光随手拍",
        badgeIcon: "image",
        order: 26,
        defaultCount: 1,
        maxFiles: 3,
        avatarUrl: "/images/skills/buyer-show-ugc-avatar.webp",
        uploadSlots: [
            {
                id: "product",
                label: "添加商品实物",
                iconType: "product",
                semanticTag: "实物商品",
                description: "上传收到的商品实物图",
            },
            {
                id: "model",
                label: "添加人物/手部 (可选)",
                iconType: "model",
                optional: true,
                semanticTag: "手持/日常人物",
                description: "上传手部或日常模特图",
            },
        ],
        placeholder: "上传商品图，可补充拍摄环境（如家中小客厅、办公室工位、梳妆台随手拍）与日常真实使用动作。",
        instructions: "生成彻底去除AI虚假感与影棚光斑的真实买家秀UGC随手拍。模拟主流旗舰智能手机广角主摄直出质感，包含轻微日常室内自然弱散光、真实生活场景的轻微杂物与微弱手机传感器噪点，呈现令人信服的真实消费者购买体验。",
        avoid: ["影棚级无暇精修", "塑料反光", "五星级过度布光", "AI手部畸形"],
        showcaseTitle: "真实买家秀随拍效果示例",
        showcaseSubtitle: "去影棚化 CCD 街头随拍、生活真实感买家秀",
        showcaseImageUrl: "/images/skills/buyer-show-ugc.webp",
    },
    {
        id: "promo-poster",
        categoryId: "social",
        name: "营销大促海报",
        subtitle: "商业级构图预留文案排版位",
        description: "商业级构图预留文案排版位",
        badgeIcon: "shopping-bag",
        order: 27,
        defaultCount: 1,
        maxFiles: 3,
        avatarUrl: "/images/skills/promo-poster-avatar.webp",
        uploadSlots: [
            {
                id: "product",
                label: "添加主推单品",
                iconType: "product",
                semanticTag: "主推单品",
                description: "上传大促主打爆款商品图",
            },
            {
                id: "bg_ref",
                label: "添加促销背景参考 (可选)",
                iconType: "background",
                optional: true,
                semanticTag: "促销背景",
                description: "上传大促展台或节日氛围背景",
            },
        ],
        placeholder: "可补充促销主题（如年终盛典、新季首发、双11狂欢）、视觉风格（3D立体展台/流光溢彩/国潮大红）与文案排版预留区。",
        instructions: "以@图片1为绝对视觉核心，生成电商S级大促营销主KV海报。具备极强视觉冲击力的大片级展台构图、动感流光与促销氛围粒子，画面顶部与底部必须严格预留 35%~45% 的纯净安全空白区（Negative Space），便于品牌后续排版大幅活动文案与促销价格标签。",
        avoid: ["画面太满没有文案位", "促销元素杂乱抢戏", "商品主体不突出", "边缘裁切不当"],
        showcaseTitle: "营销大促海报效果示例",
        showcaseSubtitle: "商业级 Key Visual 主视觉与促销排版构图",
        showcaseImageUrl: "/images/skills/promo-poster.webp",
    },
    {
        id: "ghost-mannequin-3d",
        categoryId: "ecommerce",
        name: "3D 幽灵模特图",
        subtitle: "服装立体镂空隐形模特效果",
        description: "服装立体镂空隐形模特效果",
        badgeIcon: "shirt",
        order: 28,
        defaultCount: 1,
        maxFiles: 3,
        avatarUrl: "/images/skills/ghost-mannequin-3d-avatar.webp",
        uploadSlots: [
            {
                id: "garment",
                label: "添加服装平铺/挂拍图",
                iconType: "top",
                semanticTag: "服装",
                description: "上传单件服装的正面平铺或挂拍图",
            },
            {
                id: "back_inside",
                label: "添加领口内衬/内标参考 (可选)",
                iconType: "fabric",
                optional: true,
                semanticTag: "领标内衬",
                description: "上传衣领内侧标签或内衬纹理",
            },
        ],
        placeholder: "上传服装平铺或挂拍图，可补充面料厚度、版型挺括度或特定拍摄角度。",
        instructions: "严格以@图片1的服装款式、面料材质、剪裁走线与色彩细节为基准，生成高定电商标准的3D幽灵模特（Invisible / Ghost Mannequin）立体透视展示图。模特身体完全隐形镂空，仅保留服装自然饱满的3D穿着立体轮廓与悬浮感，衣领后内衬、商标及内侧缝线自然展现。纯白影棚背景（#FFFFFF），商业柔光箱均匀对称打光，下方带有柔和自然的阴影投射。",
        avoid: ["出现任何实体人体或塑料假人模特", "领口内部封闭死黑", "服装塌陷无立体感", "面料质感失真", "阴影生硬突兀"],
        showcaseTitle: "3D 幽灵模特图效果示例",
        showcaseSubtitle: "隐形模特立体镂空展示，领标细节自然完整",
        showcaseImageUrl: "/images/skills/ghost-mannequin-3d.webp",
    },
    {
        id: "before-after",
        categoryId: "ecommerce",
        name: "功效前后对比图",
        subtitle: "同画幅左右双拼效果直观对比",
        description: "同画幅左右双拼效果直观对比",
        badgeIcon: "sparkles",
        order: 29,
        defaultCount: 1,
        maxFiles: 3,
        avatarUrl: "/images/skills/before-after-avatar.webp",
        uploadSlots: [
            {
                id: "product",
                label: "添加核心产品",
                iconType: "product",
                semanticTag: "核心产品",
                description: "上传护肤/个护/清洁/数码等产品图",
            },
            {
                id: "ref_state",
                label: "使用前状态参考 (可选)",
                iconType: "general",
                optional: true,
                semanticTag: "使用前状态",
                description: "上传使用前有瑕疵/脏污/暗沉等状态参考",
            },
        ],
        placeholder: "上传产品图，可补充对比场景（如肌肤暗沉vs透亮白皙、厨房油污vs一擦即净、受损干枯发质vs水润光泽）。",
        instructions: "以@图片1为核心产品，生成电商高转化率的左右（或上下）双拼功效前后对比图（Before & After Comparison）。左侧（Before）真实呈现使用产品前的瑕疵/问题状态（如干燥、暗沉、油污、杂乱），画面色调偏冷暗；右侧（After）呈现使用产品后的显著改善与理想治愈状态（如水润亮白、洁净如新、光泽顺滑），打光温暖明亮。中间配有极细中性分割线，左右主体构图比例与视角严格保持一致，产品本身放置于画面正下方或中央，彰显核心功效背书。",
        avoid: ["虚假夸大畸形效果", "左右视角不一致", "过度磨皮假面", "分割线粗糙突兀", "产品变形失真"],
        showcaseTitle: "功效前后对比图效果示例",
        showcaseSubtitle: "专业级双拼对照排版，直观展现产品使用蜕变",
        showcaseImageUrl: "/images/skills/before-after.webp",
    },
    {
        id: "ingredient-infographic",
        categoryId: "ecommerce",
        name: "核心成分科技图",
        subtitle: "产品核心天然提取物与微观科技解析",
        description: "产品核心天然提取物与微观科技解析",
        badgeIcon: "sparkles",
        order: 30,
        defaultCount: 1,
        maxFiles: 3,
        avatarUrl: "/images/skills/ingredient-infographic-avatar.webp",
        uploadSlots: [
            {
                id: "product",
                label: "添加核心单品",
                iconType: "product",
                semanticTag: "核心单品",
                description: "上传护肤/美妆/保健/食品产品图",
            },
            {
                id: "ingredient_ref",
                label: "添加核心成分参考 (可选)",
                iconType: "material",
                optional: true,
                semanticTag: "核心成分",
                description: "上传植物萃取物/微观分子/矿物等成分图",
            },
        ],
        placeholder: "上传产品图，可补充核心成分（如积雪草、玻色因分子球、山茶花、烟酰胺微晶）与科技氛围（冷调微观实验室/晨露植物纯净感）。",
        instructions: "以@图片1为绝对视觉核心，生成电商详情页高定核心成分与配方科技感信息图（Ingredient & Technology Infographic）。产品周围错落有致地环绕其核心原料提取物（如娇艳带有水珠的天然植物、微观透亮的活性分子水滴、纯净发光微胶囊粒子），采用微距大景深电影感摄影风格。画面周围预留清晰的数据标注与功效解析文本展示区，色彩纯净通透，兼具高端现代护肤科技感与天然有机生命力。",
        avoid: ["成分喧宾夺主遮挡产品", "元素漂浮违和无重力感", "画面杂乱无排版空间", "产品标签模糊"],
        showcaseTitle: "核心成分科技图效果示例",
        showcaseSubtitle: "天然活性萃取与微观分子科技视觉，赋能产品硬核卖点",
        showcaseImageUrl: "/images/skills/ingredient-infographic.webp",
    },
    {
        id: "flat-lay-aesthetic",
        categoryId: "ecommerce",
        name: "平铺美学摆拍",
        subtitle: "俯视网格与惬意生活场景平铺图",
        description: "俯视网格与惬意生活场景平铺图",
        badgeIcon: "shopping-bag",
        order: 31,
        defaultCount: 1,
        maxFiles: 3,
        avatarUrl: "/images/skills/flat-lay-aesthetic-avatar.webp",
        uploadSlots: [
            {
                id: "product",
                label: "添加主陈列商品",
                iconType: "product",
                semanticTag: "主商品",
                description: "上传服饰穿搭、数码日常、彩妆文具等平铺主体",
            },
            {
                id: "prop_ref",
                label: "添加搭配配饰/道具 (可选)",
                iconType: "general",
                optional: true,
                semanticTag: "搭配配饰",
                description: "上传包袋、杂志、咖啡杯、首饰等配饰参考",
            },
        ],
        placeholder: "上传商品图，可补充平铺风格（如极简整齐网格Knolling、慵懒惬意咖啡馆、周末旅行打包EDC随身物）。",
        instructions: "严格以@图片1为主体，生成专业时尚杂志级的垂直90度俯视平铺摄影图（Flat Lay / Knolling Style）。商品与搭配的精选道具（如质感面料衬底、杂志书籍、极简咖啡杯、绿植干花、精品首饰等）经过考究的几何美学比例对称或自然散点排列。采用柔和均匀的自然漫射顶光，带有微弱柔和阴影，纹理细节纤毫毕现，色彩优雅和谐，充满高品味生活格调。",
        avoid: ["视角倾斜非正俯视", "透视变形", "道具过多杂乱喧宾夺主", "硬光杂乱阴影重叠"],
        showcaseTitle: "平铺美学摆拍效果示例",
        showcaseSubtitle: "90°垂直顶视美学，时尚杂志级生活穿搭与好物陈列",
        showcaseImageUrl: "/images/skills/flat-lay-aesthetic.webp",
    },
    {
        id: "garment-extract",
        categoryId: "ecommerce",
        name: "模特图服装提取",
        subtitle: "从真人街拍/模特照提取纯净单品白底图",
        description: "从真人街拍/模特照提取纯净单品白底图",
        badgeIcon: "shirt",
        order: 32,
        defaultCount: 1,
        maxFiles: 3,
        avatarUrl: "/images/skills/garment-extract-avatar.webp",
        uploadSlots: [
            {
                id: "model_shot",
                label: "添加真人模特穿搭照",
                iconType: "model",
                semanticTag: "模特原图",
                description: "上传模特穿着目标服装的街拍、棚拍或生活照",
            },
        ],
        placeholder: "上传模特穿搭照，可补充需提取的单品目标（如“提取模特穿的复古水洗牛仔外套”或“提取碎花连衣裙”）。",
        instructions: "精准识别并分离提取@图片1中模特身上穿着的指定服装单品，将其转换为纯净电商标准挂拍或平铺白底单品图。完整还原服装真实的原始版型、剪裁轮廓、缝线纹理、拉链扣子五金与真实色彩，剔除模特身体部位、无关饰品以及复杂原背景。放置于纯白背景（#FFFFFF）正中央，呈现高端电商单品标准的商业平光，带有轻微真实的底部阴影。",
        avoid: ["遗留人体皮肤残影", "服装边缘裁切破损", "拉链纽扣等五金变形", "色彩产生偏差失真"],
        showcaseTitle: "模特图服装提取效果示例",
        showcaseSubtitle: "一键分离模特穿搭，还原纯净高保真电商单品挂拍图",
        showcaseImageUrl: "/images/skills/garment-extract.webp",
    },
    {
        id: "clothing-dewrinkle",
        categoryId: "enhance",
        name: "衣物智能去皱",
        subtitle: "抚平衣物折痕与压褶，恢复挺括垂顺",
        description: "抚平衣物折痕与压褶，恢复挺括垂顺",
        badgeIcon: "sparkles",
        order: 33,
        defaultCount: 1,
        maxFiles: 3,
        avatarUrl: "/images/skills/clothing-dewrinkle-avatar.webp",
        uploadSlots: [
            {
                id: "garment",
                label: "添加褶皱服装图",
                iconType: "top",
                semanticTag: "褶皱服装",
                description: "上传有褶皱折痕的挂拍、平铺或模特上身图",
            },
        ],
        placeholder: "上传有褶皱的服装图，可补充面料类型（如丝绸光泽垂顺、羊绒柔软挺括、纯棉平整亲肤）。",
        instructions: "严格保持@图片1中服装的整体版型、花色印花、剪裁缝线、纽扣五金及整体光影完全不变。智能识别并抚平衣物表面因包装折叠、挤压产生的非设计性深浅褶皱与杂乱折痕，恢复高级面料自然的平整挺括与垂顺质感。保留面料天然细腻的织物纤维肌理，杜绝过度磨皮带来的塑料平滑感，达到商业级高端蒸汽熨烫后的全新成衣上镜质感。",
        avoid: ["磨平织物天然纹理导致塑料感", "误消除服装本身的百褶/设计褶皱", "服装版型走形", "颜色明暗突变"],
        showcaseTitle: "衣物智能去皱效果示例",
        showcaseSubtitle: "蒸汽熨烫级平整抚平，保留天然织物纤维质感",
        showcaseImageUrl: "/images/skills/clothing-dewrinkle.webp",
    },
];
