import type { VideoSkillCategory, VideoWorkbenchSkill } from "../types/video-skill-contract";

export const BUILTIN_VIDEO_CATEGORIES: VideoSkillCategory[] = [
    { id: "recommend", name: "推荐", iconName: "recommend", order: 0 },
    { id: "ecommerce", name: "电商带货", iconName: "ecommerce", order: 1 },
    { id: "store", name: "同城到店", iconName: "store", order: 2 },
    { id: "brand", name: "品牌广告", iconName: "brand", order: 3 },
    { id: "drama", name: "剧情短片", iconName: "drama", order: 4 },
];

export const BUILTIN_VIDEO_SKILLS: VideoWorkbenchSkill[] = [
    // ════════════════════════════════════════════════════════════════
    // 推荐分类 (对齐截图 2、5、6)
    // ════════════════════════════════════════════════════════════════
    {
        id: "reference-replication",
        categoryId: "recommend",
        secondaryCategoryIds: ["recommend", "ecommerce"],
        name: "深度复刻",
        subtitle: "解构原片，精准换人换品换背景",
        description: "提取参考视频动作、运镜与节奏，结合用户商品、人物、背景与声音素材，推演连锁状态变化并生成 Seedance-2.0 专用复刻提示词。",
        isRecommended: true,
        order: 0,
        defaultDurationSec: 10,
        defaultLanguage: "zh",
        scriptType: "smart",
        shootingStyle: "smart",
        primaryPlatform: "douyin",
        badgeIcon: "video",
        avatarUrl: "/images/skills/buyer-show-ugc-avatar.webp",
        placeholder: "补充说明：可输入复刻要求，修改台词或商品细节，也可@引用已上传素材。输入后可直接立即生成，或点击【复刻助手】推演生成专业复刻提示词。",
        suggestedQuickPhrases: [
            "保持原片口播台词不变",
            "突出商品材质与高光质感",
            "人物表情自然自信",
            "环境光影与新背景完全融合",
        ],
    },
    {
        id: "livestream-pitch",
        categoryId: "ecommerce",
        secondaryCategoryIds: ["recommend", "ecommerce"],
        name: "口播带货",
        subtitle: "真人推荐，建立购买信任",
        description: "真人出镜对镜讲解，结合生活场景与真诚口吻建立信任感。",
        isRecommended: true,
        order: 1,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "livestream_pitch",
        shootingStyle: "talking_head",
        primaryPlatform: "douyin",
        badgeIcon: "video",
        avatarUrl: "/images/skills/buyer-show-ugc-avatar.webp",
        placeholder: "可补充主播人设、目标受众或需要强调的重点卖点...",
        suggestedQuickPhrases: [
            "真实闺蜜聊天口吻",
            "自用回购真诚力荐",
            "直击产品核心痛点",
            "拒绝推销说明书广告腔",
            "引导点击左下角看同款",
        ],
    },
    {
        id: "promotional-conversion",
        categoryId: "ecommerce",
        secondaryCategoryIds: ["recommend", "ecommerce"],
        name: "促销转化",
        subtitle: "放大优惠，推动立即下单",
        description: "放大优惠力度与限时特惠，直观对比推动立即下单或核销。",
        isRecommended: true,
        order: 2,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "promotional_conversion",
        shootingStyle: "unboxing_tabletop",
        primaryPlatform: "douyin",
        badgeIcon: "video",
        avatarUrl: "/images/skills/promo-poster-avatar.webp",
        placeholder: "可说明优惠幅度、赠品权益或限时抢购提示...",
        suggestedQuickPhrases: [
            "突出原价与优惠强烈反差",
            "制造限时限量紧迫感",
            "直接清晰的行动指令",
            "直击产品核心痛点",
        ],
    },
    {
        id: "store-visit",
        categoryId: "store",
        secondaryCategoryIds: ["recommend", "store"],
        name: "到店实录",
        subtitle: "真实体验，建立消费信任",
        description: "沉浸式探店全过程，还原偶发细节与真实反应，建立消费信任。",
        isRecommended: true,
        order: 3,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "store_visit",
        shootingStyle: "one_take",
        primaryPlatform: "douyin",
        badgeIcon: "video",
        avatarUrl: "/images/skills/bare-to-renovated-avatar.webp",
        placeholder: "可补充探店第一视角、特色区域或特色体验流程...",
        suggestedQuickPhrases: [
            "第一视角主观镜头进店",
            "还原环境动线与偶发细节",
            "突出真实松弛消费体验",
            "突出同城门店位置与停车",
        ],
    },
    {
        id: "group-buying",
        categoryId: "store",
        secondaryCategoryIds: ["recommend", "store"],
        name: "同城团购",
        subtitle: "突出优惠，推动到店核销",
        description: "套餐性价比直观对比，打消消费顾虑，指引同城到店核销。",
        isRecommended: true,
        order: 4,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "group_buying",
        shootingStyle: "talking_head",
        primaryPlatform: "douyin",
        badgeIcon: "video",
        avatarUrl: "/images/skills/redbook-seed-avatar.webp",
        placeholder: "可说明团购套餐内容、价格优势及核销规则...",
        suggestedQuickPhrases: [
            "直观展示团购套餐划算度",
            "打消到店消费顾虑",
            "清晰引导同城核销链路",
            "强烈对比突出差异",
        ],
    },
    {
        id: "twist-skit",
        categoryId: "drama",
        secondaryCategoryIds: ["recommend", "drama"],
        name: "反转短剧",
        subtitle: "剧情反转，制造传播记忆",
        description: "强烈预期与意料之外的转折打脸，形成高记忆点爽感与软植入。",
        isRecommended: true,
        order: 5,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "twist_skit",
        shootingStyle: "follow_shot",
        primaryPlatform: "douyin",
        badgeIcon: "video",
        avatarUrl: "/images/skills/character-realism-avatar.webp",
        placeholder: "可补充剧情人际关系、预期设想与意外反转的关键点...",
        suggestedQuickPhrases: [
            "制造强烈情绪反转",
            "用反常识观点开场",
            "产品成为反转打脸原因",
            "自然融入生活不生硬",
        ],
    },
    {
        id: "emotional-clip",
        categoryId: "drama",
        secondaryCategoryIds: ["recommend", "drama"],
        name: "情绪短片",
        subtitle: "情绪共鸣，强化内容感染",
        description: "感官治愈与温情共鸣，抚平日常疲惫，触动深层心智与向往感。",
        isRecommended: true,
        order: 6,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "emotional_clip",
        shootingStyle: "one_take",
        primaryPlatform: "xiaohongshu",
        badgeIcon: "video",
        avatarUrl: "/images/skills/cinematic-storyboard-avatar.webp",
        placeholder: "可补充情绪基调、慢节奏生活细节或治愈体验描述...",
        suggestedQuickPhrases: [
            "突出生活治愈感与松弛体验",
            "电影级自然光影质感",
            "疲惫情绪被温柔抚平",
            "好物忍不住分享的松弛感",
        ],
    },

    // ════════════════════════════════════════════════════════════════
    // 电商带货分类 (对齐截图 7)
    // ════════════════════════════════════════════════════════════════
    {
        id: "scene-seeding",
        categoryId: "ecommerce",
        name: "场景种草",
        subtitle: "植入场景，激发使用需求",
        description: "将商品融入具体生活或工作场景，自然激发潜在使用需求。",
        order: 7,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "lifestyle",
        shootingStyle: "follow_shot",
        primaryPlatform: "xiaohongshu",
        badgeIcon: "video",
        avatarUrl: "/images/skills/product-lifestyle-avatar.webp",
        placeholder: "可补充具体使用场景，如早八通勤、露营聚会、居家独处等...",
        suggestedQuickPhrases: [
            "利用新奇场景开场",
            "真实痛点引出需求",
            "生活切片具象生动",
            "强调感官体验爽感",
        ],
    },
    {
        id: "pain-point-solve",
        categoryId: "ecommerce",
        secondaryCategoryIds: ["recommend", "ecommerce"],
        name: "痛点解决",
        subtitle: "直击痛点，展示解决效果",
        description: "精准直击现实困扰与小尴尬，自然引入商品消除焦虑与烦恼。",
        order: 8,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "pain_point",
        shootingStyle: "talking_head",
        primaryPlatform: "douyin",
        badgeIcon: "video",
        avatarUrl: "/images/skills/before-after-avatar.webp",
        placeholder: "可说明目标用户的核心痛点、困扰或急需解决的问题...",
        suggestedQuickPhrases: [
            "直击产品核心痛点",
            "真实痛点引出需求",
            "前后对比差异明显",
            "产品作为解题关键自然进入",
        ],
    },
    {
        id: "feature-demo",
        categoryId: "ecommerce",
        name: "功能演示",
        subtitle: "演示功能，证明产品价值",
        description: "硬核直观演示核心功能与工艺细节，用事实与效果证明价值。",
        order: 9,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "qianchuan",
        shootingStyle: "unboxing_tabletop",
        primaryPlatform: "douyin",
        badgeIcon: "video",
        avatarUrl: "/images/skills/detail-8pack-avatar.webp",
        placeholder: "可说明需要特写的功能步骤、材质耐用性或实验对比...",
        suggestedQuickPhrases: [
            "强烈对比突出差异",
            "微距特写材质工艺",
            "用效果与数据说话",
            "黄金前3秒硬核截停",
        ],
    },
    {
        id: "selling-hook",
        categoryId: "ecommerce",
        name: "卖点钩子",
        subtitle: "悬念开场，反常识突出卖点",
        description: "立反常识 flag 制造悬念，意外反转打脸突出核心卖点。",
        order: 10,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "selling_hook",
        shootingStyle: "smart",
        primaryPlatform: "douyin",
        badgeIcon: "video",
        avatarUrl: "/images/skills/product-hero-avatar.webp",
        placeholder: "可补充令人好奇的反常识观点或悬念问题...",
        suggestedQuickPhrases: [
            "用反常识观点开场",
            "制造强烈情绪反转",
            "前3秒立观众会信的flag",
            "反转与卖点深度绑定",
        ],
    },
    {
        id: "object-pov",
        categoryId: "ecommerce",
        name: "物品拟人",
        subtitle: "第一人称自述，反差萌亮出绝活",
        description: "商品以第一人称口吻自述吐槽，反差萌自嘲吸睛亮出独家绝活。",
        order: 11,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "object_pov",
        shootingStyle: "one_take",
        primaryPlatform: "douyin",
        badgeIcon: "video",
        avatarUrl: "/images/skills/flat-lay-aesthetic-avatar.webp",
        placeholder: "可说明拟人性格（如傲娇、毒舌、贴心管家等）及主要吐槽点...",
        suggestedQuickPhrases: [
            "商品第一人称自述吐槽",
            "反差萌性格强化记忆点",
            "在互动中亮出独家本领",
        ],
    },

    // ════════════════════════════════════════════════════════════════
    // 同城到店分类 (对齐截图 8)
    // ════════════════════════════════════════════════════════════════
    {
        id: "store-discovery",
        categoryId: "store",
        name: "门店发现",
        subtitle: "突出特色，制造到店理由",
        description: "聚焦门头设计、空间美学、环境动线与打卡亮点，制造进店理由。",
        order: 12,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "store_discovery",
        shootingStyle: "follow_shot",
        primaryPlatform: "douyin",
        badgeIcon: "video",
        avatarUrl: "/images/skills/furniture-in-situ-avatar.webp",
        placeholder: "可说明门店空间特色、出片机位或特别陈设...",
        suggestedQuickPhrases: [
            "利用新奇场景开场",
            "聚焦空间美学与动线",
            "突出同城必打卡理由",
            "突出同城门店位置与停车",
        ],
    },
    {
        id: "signature-experience",
        categoryId: "store",
        name: "招牌体验",
        subtitle: "聚焦招牌，证明门店价值",
        description: "深度特写招牌菜品制作或王牌服务体验，证明绝对核心价值。",
        order: 13,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "signature_experience",
        shootingStyle: "unboxing_tabletop",
        primaryPlatform: "douyin",
        badgeIcon: "video",
        avatarUrl: "/images/skills/ingredient-infographic-avatar.webp",
        placeholder: "可说明招牌菜品或核心服务项目的制作流程与亮点...",
        suggestedQuickPhrases: [
            "深度特写招牌高光瞬间",
            "感官冲击与食欲满满",
            "沉浸式声画细节体验",
            "证明门店王牌硬实力",
        ],
    },
    {
        id: "weekend-discovery",
        categoryId: "store",
        name: "周末去哪",
        subtitle: "周末生活纪实，营造打卡向往",
        description: "以城市探索者自用视角，分享周末放松好去处与高品质体验。",
        order: 14,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "lifestyle",
        shootingStyle: "follow_shot",
        primaryPlatform: "xiaohongshu",
        badgeIcon: "video",
        avatarUrl: "/images/skills/tile-flooring-avatar.webp",
        placeholder: "可说明适合的休闲场景（如闺蜜下午茶、家庭聚会、独处放空等）...",
        suggestedQuickPhrases: [
            "松弛感满满的周末生活",
            "逃离城市喧嚣的治愈角落",
            "小众出片宝藏地点",
            "真实探店不踩雷指引",
        ],
    },
    {
        id: "street-interview",
        categoryId: "store",
        name: "街头实测",
        subtitle: "主持人实地问答，建立现场感",
        description: "以主持人现场随机问答形式，用路人与顾客的真实反馈建立公信力。",
        order: 15,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "qianchuan",
        shootingStyle: "street_interview",
        primaryPlatform: "douyin",
        badgeIcon: "video",
        avatarUrl: "/images/skills/virtual-try-on-avatar.webp",
        placeholder: "可说明街采的核心提问或现场对比测试内容...",
        suggestedQuickPhrases: [
            "真实随机路人互动反馈",
            "充满现场感与真实代入感",
            "打破疑虑证实口碑",
        ],
    },

    // ════════════════════════════════════════════════════════════════
    // 品牌广告分类 (对齐截图 9)
    // ════════════════════════════════════════════════════════════════
    {
        id: "brand-advocacy",
        categoryId: "brand",
        name: "品牌主张",
        subtitle: "传递理念，建立价值认同",
        description: "以高度凝练的影像语言传递品牌核心价值观与态度，唤起心理共鸣。",
        order: 16,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "story",
        shootingStyle: "brand_awareness",
        primaryPlatform: "channels",
        badgeIcon: "video",
        avatarUrl: "/images/skills/image-refinement-avatar.webp",
        placeholder: "可说明品牌核心哲学、生活主张或目标受众的精神追求...",
        suggestedQuickPhrases: [
            "传递品牌深度人文理念",
            "建立价值观精神认同",
            "电影级考究光影与构图",
            "克制且有力量感的对白",
        ],
    },
    {
        id: "brand-story",
        categoryId: "brand",
        name: "品牌故事",
        subtitle: "讲述故事，强化品牌信任",
        description: "讲述匠心起源、研发历程或真实用户相伴故事，塑造沉淀厚度。",
        order: 17,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "story",
        shootingStyle: "brand_awareness",
        primaryPlatform: "channels",
        badgeIcon: "video",
        avatarUrl: "/images/skills/material-macro-texture-avatar.webp",
        placeholder: "可说明创始初衷、工艺坚持或动人故事脉络...",
        suggestedQuickPhrases: [
            "娓娓道来的真实故事",
            "突显专注执着的匠心精神",
            "加深对品牌长久信赖",
        ],
    },
    {
        id: "lifestyle-brand",
        categoryId: "brand",
        name: "生活方式",
        subtitle: "塑造场景，建立品牌向往",
        description: "描绘品牌倡导的理想生活切片与美学状态，让受众产生美好向往。",
        order: 18,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "lifestyle",
        shootingStyle: "one_take",
        primaryPlatform: "xiaohongshu",
        badgeIcon: "video",
        avatarUrl: "/images/skills/clothing-dewrinkle-avatar.webp",
        placeholder: "可说明具体的生活美学调性，如极简主义、精致松弛、自然原野等...",
        suggestedQuickPhrases: [
            "塑造令人向往的美好生活",
            "高级审美质感与呼吸感",
            "好物无声融入生活日常",
        ],
    },
    {
        id: "creative-concept",
        categoryId: "brand",
        name: "创意概念",
        subtitle: "创意表达，强化品牌记忆",
        description: "借助艺术化意象、超现实视觉或独特隐喻，形成强烈记忆烙印。",
        order: 19,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "selling_hook",
        shootingStyle: "brand_awareness",
        primaryPlatform: "channels",
        badgeIcon: "video",
        avatarUrl: "/images/skills/exploded-view-avatar.webp",
        placeholder: "可说明意向隐喻符号、概念对比或视觉冲击点...",
        suggestedQuickPhrases: [
            "超现实艺术化创意视听",
            "强烈视觉反差留下深刻印象",
            "前沿先锋的设计感表达",
        ],
    },

    // ════════════════════════════════════════════════════════════════
    // 剧情短片分类 (对齐截图 10)
    // ════════════════════════════════════════════════════════════════
    {
        id: "dialogue-skit",
        categoryId: "drama",
        name: "对话短剧",
        subtitle: "人物冲突，推动剧情发展",
        description: "双人或多人生动对话驱动剧情，在日常互动与拌嘴中带出产品亮点。",
        order: 20,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "dialogue_skit",
        shootingStyle: "talking_head",
        primaryPlatform: "douyin",
        badgeIcon: "video",
        avatarUrl: "/images/skills/face-3views-avatar.webp",
        placeholder: "可说明角色关系（如室友、情侣、同事、母女等）及对话矛盾点...",
        suggestedQuickPhrases: [
            "生动鲜活的人物对白台词",
            "熟人日常互怼与戏剧张力",
            "在互动交锋中引出产品",
            "生活气息浓郁接地气",
        ],
    },
    {
        id: "suspense-skit",
        categoryId: "drama",
        name: "悬念短剧",
        subtitle: "设置悬念，持续吸引观看",
        description: "开局抛出好奇谜团或反常现象，层层递进吸引持续留存，最终揭晓答案。",
        order: 21,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "suspense_skit",
        shootingStyle: "one_take",
        primaryPlatform: "douyin",
        badgeIcon: "video",
        avatarUrl: "/images/skills/character-staging-avatar.webp",
        placeholder: "可说明开头设置的悬念疑问，以及最终与商品相关的解答...",
        suggestedQuickPhrases: [
            "开局3秒抛出致命好奇疑问",
            "层层剥茧拉高完播留存",
            "出人意料的惊喜揭秘",
        ],
    },
    {
        id: "product-placement",
        categoryId: "drama",
        name: "产品植入",
        subtitle: "融入剧情，自然传递价值",
        description: "自然推进的生活剧情中，产品或服务作为关键道具无痕出镜。",
        order: 22,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "product_placement",
        shootingStyle: "smart",
        primaryPlatform: "douyin",
        badgeIcon: "video",
        avatarUrl: "/images/skills/clothing-redesign-avatar.webp",
        placeholder: "可说明剧情的主线事件，以及产品在何种情境下作为道具出镜...",
        suggestedQuickPhrases: [
            "剧情驱动而非广告推销",
            "产品作为关键道具自然推进",
            "润物细无声的软性种草",
        ],
    },
    {
        id: "story-conflict",
        categoryId: "drama",
        name: "剧情故事",
        subtitle: "戏剧冲突，商品成为关键破局",
        description: "经典戏剧人物冲突，面对现实困境时，商品或服务成为破局的关键钥匙。",
        order: 23,
        defaultDurationSec: 15,
        defaultLanguage: "zh",
        scriptType: "story",
        shootingStyle: "smart",
        primaryPlatform: "douyin",
        badgeIcon: "video",
        avatarUrl: "/images/skills/character-4views-avatar.webp",
        placeholder: "可说明主角遭遇的戏剧冲突或挑战，以及如何破局...",
        suggestedQuickPhrases: [
            "经典戏剧张力与人物困境",
            "峰回路转的破局体验",
            "兼具观赏性与商业软转化",
        ],
    },
];

export function findVideoSkill(id: string): VideoWorkbenchSkill | undefined {
    return BUILTIN_VIDEO_SKILLS.find((skill) => skill.id === id);
}

export const getVideoSkillById = findVideoSkill;
export const VIDEO_SKILL_CATEGORIES = BUILTIN_VIDEO_CATEGORIES;

export function getVideoSkillsByCategory(categoryId: string, keyword?: string): VideoWorkbenchSkill[] {
    const trimmed = keyword?.trim().toLowerCase() || "";
    return BUILTIN_VIDEO_SKILLS.filter((skill) => {
        const matchesCategory =
            categoryId === "recommend"
                ? Boolean(skill.isRecommended || skill.secondaryCategoryIds?.includes("recommend"))
                : skill.categoryId === categoryId || skill.secondaryCategoryIds?.includes(categoryId);

        if (!matchesCategory) return false;
        if (!trimmed) return true;
        return (
            skill.name.toLowerCase().includes(trimmed) ||
            skill.subtitle.toLowerCase().includes(trimmed) ||
            skill.description.toLowerCase().includes(trimmed)
        );
    });
}

export function filterVideoSkills(categoryId: string, keyword?: string): VideoWorkbenchSkill[] {
    if (categoryId === "all") {
        const trimmed = keyword?.trim().toLowerCase() || "";
        if (!trimmed) return BUILTIN_VIDEO_SKILLS;
        return BUILTIN_VIDEO_SKILLS.filter((skill) =>
            skill.name.toLowerCase().includes(trimmed) ||
            skill.subtitle.toLowerCase().includes(trimmed) ||
            skill.description.toLowerCase().includes(trimmed) ||
            skill.suggestedQuickPhrases?.some((p) => p.toLowerCase().includes(trimmed))
        );
    }
    return getVideoSkillsByCategory(categoryId, keyword);
}
